name: Test Tunnel

on:
    workflow_dispatch:

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - run: npm install

      - name: Start LambdaTest Tunnel
        id: tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v1
        with:
         user: LT_EMAIL
         accessKey: Mavens_7075
         tunnelName: "test tunnel"
         tunnelArgs: "--port 33429"
         
      - name: Run Test Case
        env:
         LT_USERNAME: LT_ACCESS_KEY
         LT_ACCESS_KEY: Royal_7075
         LT_TUNNEL_NAME: "test tunnel"
         run: npm run test

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
