name: Node.js CI
on:
 workflow_dispatch:
 push:
      branches: [ "master" ]



jobs:
   allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2



      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Install Dependencies
        run: npm install
      - name: setup Latest Chrome Driver
        run: npm run chromeDriverUpdate
      - name: install chromedriver version 109
        run: npm i chromedriver@109 --save -dev
      - name: Executing the Test Scripts
        run: npm run makeMyTrip  



      - name: Allure Report action from marketplace
        uses: AnilCa1905/simple-elf-Repo@master
        if: always()
        #id: allure-report
        with:
          allure_results: test\.artifacts\allure-report
          #gh_pages: gh-pages
          #allure_report: test\.artifacts\allure-report
          allure_history: allure-history
          keep_reports: 20




      - name: Deploy report to Github Pages
        if: always()
        uses: AnilCa1905/Peaceiris-gh_pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: test/.artifacts/allure-report
    
